rocketpool:
  storageAddress: 0xA85A8022E8F28E49B8BBfb792f93ee914B342C3b
smartnode:
  projectName: rocketpool
  image: rocketpool/smartnode:v0.0.9
  passwordPath: /.rocketpool/data/password
  walletPath: /.rocketpool/data/wallet
  validatorKeychainPath: /.rocketpool/data/validators
chains:
  eth1:
    provider: http://eth1:8545
    client:
      options:
      - id: geth
        name: Geth
        desc: made by the Ethereum Foundation
        image: ethereum/client-go:v1.9.24
        link: https://geth.ethereum.org/
        params:
        - name: Ethstats Label
          desc: optional - for reporting Eth 1.0 node status to ethstats.net
          env: ETHSTATS_LABEL
        - name: Ethstats Login
          desc: optional - for reporting Eth 1.0 node status to ethstats.net
          env: ETHSTATS_LOGIN
      - id: infura
        name: Infura
        desc: use infura.io as a light client for Eth 1.0 - not recommended for use in production
        image: rocketpool/smartnode-pow-proxy:v0.0.3
        link: https://infura.io/
        params:
        - name: Infura Project ID
          desc: the ID of your project created in Infura
          env: INFURA_PROJECT_ID
          regex: ^[0-9a-fA-F]{32}$
          required: true
      - id: custom
        name: Custom
        desc: use a custom Eth 1.0 client at a specified address (does not work on localhost)
        image: rocketpool/smartnode-pow-proxy:v0.0.3
        params:
        - name: Provider URL
          desc: the Eth 1.0 client HTTP server address
          env: PROVIDER_URL
          required: true
  eth2:
    provider: eth2:5052
    client:
      options:
      - id: lighthouse
        name: Lighthouse
        desc: made by Sigma Prime
        image: sigp/lighthouse:v1.0.3
        link: https://sigmaprime.io/
        params:
        - name: Custom Graffiti
          desc: optional - for adding custom text to signed Eth 2.0 blocks - 16 chars max
          env: CUSTOM_GRAFFITI
          regex: ^.{0,16}$
      - id: prysm
        name: Prysm
        desc: made by Prysmatic Labs
        beaconImage: prysmaticlabs/prysm-beacon-chain:HEAD-fc7c67-debug #v1.0.3
        validatorImage: prysmaticlabs/prysm-validator:HEAD-fc7c67-debug #v1.0.3
        link: https://prysmaticlabs.com/
        params:
        - name: Custom Graffiti
          desc: optional - for adding custom text to signed Eth 2.0 blocks - 16 chars max
          env: CUSTOM_GRAFFITI
          regex: ^.{0,16}$
